### ISSUE TITLE
Page template does not render lists properly

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#16]
I found that the slide templates that are available for download have definitions for lists (e.g. using green dots for bulleted lists).

The css template for the web site seems to be missing some of those definitions.
(E.g. when using &lt;ul&gt; ... &lt;/ul&gt; on a project page I don't get indents nor bullets, see the Legnaro (LNL) page.)

**Comment by ralphlange** [comment]
Ping!

Just added yet another project that uses a list. This is increasingly annoying.

**Comment by ttkorhonen** [comment]
I try to see if Keijo could take a look at this. Otherwise somebody else has to pick up this issue. I am not sure if Dirk is the right address for this issue.

**Comment by ralphlange** [comment]
Taking him off, then. Wasn't aware of that.

**Comment by ttkorhonen** [comment]
Keijo promised to take a look at this - when he finds the time. I hope in a few days but cannot promise.

**Comment by keijokorhonen** [comment]
The issue has been fixed. All unordered lists should display a small green dot next to it, as well as be indented. I have only applied the changes to project pages, since as far as I understand that's where the issue came up. 

Should we have the same type of green dots for all lists on the website or instead use the grey dots found on some other pages (like the How-to documents) for the projects too?

**Comment by ralphlange** [comment]
That's a question for @epicDirk ?

**Comment by ralphlange** [comment]
Reassigning to Dirk to answer the design question raised:
What's the design for bulleted lists on the web site?

**Comment by keijokorhonen** [comment]
We will use black dots for consistency across the site. This should be fixed for all projects as well as every other list used.
