### ISSUE TITLE
Layout for non-touch (non-mobile) displays

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-base/website#6]
The layout contains much empty space. I see that this improves usability for touch screens but it is annoying on non-touch screen devices, in particular on wide-screen laptops. There is a lot of vertical scrolling needed while at the same time there are huge empty margins left and right and the vertical size of menu items is much larger than useful for a non-touch display.
Consider using @media (pointer: fine) CSS rules to make menus compacter for non-touch displays.

**Comment by ralphlange** [comment]
@dirk-zimoch: @keijokorhonen and @epicDirk were working on the layout, considering different screen sizes and devices.
Please re-check and close the issue if things seem good enough now.

**Comment by dirk-zimoch** [comment]
I have the impression that several pages look more "compact" now, which is nice for wide viewports with little hight.
Maybe the top menu and the footer could still be made more compact in the vertical direction. At the moment, the top menu is more than 6 times as high as the actual text in it. The same with the spacing inside the drop-down menus.

**Comment by epicDirk** [comment]
Yes dirk zimoch the menu and the banner take to much space (content is king!). The banner has at the moment aspect ratio of 1272:251 (2544x502 pixel). I will broaden (expand to left and right) the banner. My goal is aspect ratio of 48 : 5 (3840x400 pixel). Because i don't want to simply crop the picture i have to add additional content to the left and right for all the 7 banner of the website. The result will be that the banner is in height much slimmer. Further on i will try to increase the resolution of the banner so it will not look blurry on 4k screens and is more future-proof.

**Comment by epicDirk** [comment]
the first two banner are done but the typographic is not done:
[HOME](https://drive.google.com/file/d/1DYOEQlB4rYFD7CFb1I1M0qDduzGfUbUF/view?usp=sharing)
[ABOUT](https://drive.google.com/file/d/1j5bqm0K-TxlL_jVm87AqAcoYpBxsoOhK/view?usp=sharing)
work in progress =)

**Comment by dirk-zimoch** [comment]
When changing the window width, maybe you want to clip the banner left and right instead of shrinking it with constant aspect ratio. There is not much "content" on the sides of the banner, so it would look nicer to keep it centred with constant height.

**Comment by epicDirk** [comment]
good idea! it will look fine around 40% of cropping. if u crop more than that it will look ugly. Because the cubes need some space around them to look impressive. I have to talk to keijokorhonen about the scaling and cropping on how we can combine both method's with certain limits.

[CONTACT](https://drive.google.com/file/d/1f73Mja742Kk5qUHNds_cK81KbI4IdMxD/view?usp=sharing)
[NEWS EVENTS](https://drive.google.com/file/d/1mvqfkHiFFaYcTcjt68diF7KRJnJM28xb/view?usp=sharing)

**Comment by epicDirk** [comment]
[RESOURCES SUPPORT](https://drive.google.com/file/d/1w0KN_DS6H-SGc6bskDVj8bZmG_Y4wlqh/view?usp=sharing)
[LOG IN](https://drive.google.com/file/d/1qp3XTgGzay2q-ebP8oyqXzwseIrUCYz8/view?usp=sharing)

**Comment by epicDirk** [comment]
[PROJECTS](https://drive.google.com/open?id=1xt3MY2TOd5fbF9F1oxoqWqjKwIMA7dXQ)

**Comment by ralphlange** [comment]
The link labeled PROJECTS points to a file named USER. Which one is correct?

**Comment by epicDirk** [comment]
> 
> 
> The link labeled PROJECTS points to a file named USER. Which one is correct?

its just the file name
it will be projects

**Comment by epicDirk** [comment]
This is my suggestion of the new Layout with the wide banner and compressed space:
[picture](https://drive.google.com/open?id=1LRxsiEfHKV3Ew45MuY40WJi9IEhV5eGD) and [gif animation](https://drive.google.com/open?id=1TyTysVfRCyqwHHU0K7YBi7m4JmX6ZcBt)

The format of the Screen was:  2560 × 1440 pixels in a 16:9 aspect ratio
also called: QHD (Quad HD), WQHD (Wide Quad HD),or 1440p

All banners are now finished in the wide format. 4k in width. The next step would be now to integrated them in to the webpage and adjust the Webpage according to the compressed layout.

The vertical format we chose for the webpage has advantages:
-works better on vertical screens
-has more conservative look like a dina4 page 
-the design is easy to control because it is restricted in width

but also disadvantages:
-[empty-space](https://drive.google.com/file/d/1WOKxQONSVo0WfBjsbbd480lYO90XA24n/view?usp=sharing)


[PROJECTS](https://drive.google.com/open?id=1QLgHCBisd16P8oKt9bSe_Dn7PTOqr9-c) with Typo and New Flags
i added the flags of pakistan, iran and portugal

**Comment by epicDirk** [comment]
personally i browse the internet [like this](https://drive.google.com/open?id=1PAITygIF_wYRTFx3JllcsRFVsamVQ43z) and there the EPICS webpage works even in the current state quite well (2560 × 1440 pixels in a 16:9 aspect ratio)

**Comment by ralphlange** [comment]
Personally, I browse the internet [like this](https://user-images.githubusercontent.com/632191/50971056-623ff080-14e3-11e9-9e89-2322ce966403.png) so I am on DIN A4 ...

Maybe the extra space could host some otherwise useless EPICS advertising, like a random user quote or   catch phrase. ("7 is so much more than 3 + 4!")
Such an wide-screen extra would be suppressed on the narrower screens.

**Comment by epicDirk** [comment]
i would like to leave it empty. Important information needs some [negative space](https://tubikstudio.com/negative-space-in-design-tips-and-best-practices-2/).

**Comment by epicDirk** [comment]
Here are the [21 New Banners](https://drive.google.com/drive/folders/1efKEKBZQz7JVYrwJj6F6VxzoDUV5w_5X?usp=sharing). How to integrated them are described in this [picture](https://drive.google.com/file/d/1bFAwwRelezBdifWmlRXWAXQERIEVUzOu/view?usp=sharing)

**Comment by keijokorhonen** [comment]
The new banners are now in place and display the appropriate banner for small, medium and large sized screens using the srcset and sizes attributes on the HTML img tag.
