### ISSUE TITLE
Navigation broken on "projects" page

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-base/website#9]
When going from "projects" page 1 to page 2 and then click the "back" button of the browser, one does not end up on "projects" page 1 but where ever one was before the first "projects" page.
Also when going from "projects" page 2 to one of the project articles referenced there and then back, one does not end up on the same page 2 but on page 1. This makes it annoying to browse through the project articles.

**Comment by ttkorhonen** [comment]
The projects page is a "single page" that is written dynamically by Javascript. Fixing this to work with the back button is not practicable (with the current structures and plugins.) Instead we decided to do a workaround so that all content will be loaded on one page with the "load more" button. Not perfect but the best we could come up with in the available time. Better ideas would be welcome (but there will be no guarantee when they can be implemented).

**Comment by ralphlange** [comment]
Seems like a reasonable workaround.
Closing the ticket - please re-open if necessary.
